image: Visual Studio 2015   

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\cc_ublox
shallow_clone: true             

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14
        
install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin

build_script:
    - mkdir build.%PLATFORM%.%CONFIGURATION%
    - cd build.%PLATFORM%.%CONFIGURATION%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DCC_UBLOX_QT_DIR=%QTDIR% -DCC_UBLOX_FULL_SOLUTION=ON -CC_UBLOX_PLUGIN_ALL=OFF -DCC_UBLOX_PLUGIN_UBLOX8=OFF -DCC_UBLOX_PLUGIN_UBLOX7=ON -DCC_UBLOX_PLUGIN_UBLOX6=ON -DCC_UBLOX_PLUGIN_UBLOX5=ON
    - nmake install

test_script:
    - ctest 

